---
title: "Prediction of Breast Cancer Notebook"
author: 
  name: "Manrique Camacho P., Amanda Cedeño G., Iván Rodríguez C."

institute: "Universidad de Costa Rica"
lang: es  
date: today
date-format: long
format: 
  html:
    toc: true
    toc-depth: 4
    theme: united
    df-print: kable
    number-sections: true
    highlight-style: github
    fig-dpi: 600
    fig-width: 10
    fig-height: 6
    fig-align: default
    fig-format: png
editor: visual
execute: 
  echo: true
  warning: false
  message: false
---

# Breast Cancer Descriptive Analysis

## Loading Libraries

```{r}
#Data Manipulation and Visualization

pacman::p_load(
  # Data manipulation
  tidyverse,
  
  #Logistic Regression:
  magrittr, rio, here, caret, glmnet, performance, pROC, ROCR,
  
  # Other:
  ggthemes, scale
)
```

## Importing the dataset

```{r}
data <- read.csv("~/Library/CloudStorage/OneDrive-UniversidaddeCostaRica/GitHub/Predicción_Cancer/data/processed/data.csv", row.names=1)
```

## Data Inspection

```{r}
str(data)
data$Breast = as.factor(data$Breast)
data = data %>% 
  mutate_at(.vars = vars(State, Race, Education, 
                         Coverage, GeneralHealth, 
                         Children, Depression,
                         Exercise, Smoker,
                         Mammo, Breast), 
            .funs = as.factor)
```

```{r}
factor_data = data[,sapply(data, is.factor)][,-1]

for (i in 1:ncol(factor_data)){
  if (i > 13){
    
    if ((i+1) > ncol(factor_data)){
      
      break
      
    }
    
    else{
     
      print(round(proportions(as.matrix(table(factor_data$Breast, factor_data[,i+1])),1)*100,1))
      
    }
    
    
  }
  else{
    
    print(round(proportions(as.matrix(table(factor_data$Breast, factor_data[,i])),1)*100,1))
    
  }
}
```
```{r}
ggdata = data.frame(matrix(data = c("Sí","Sí","No","No",
                         "Realizado Mamografía", "No Realizado Mamografía","Realizado Mamografía", "No Realizado Mamografía",
                         99.5, 0.5, 94.5, 5.5),nrow = 4, ncol = 3))
colnames(ggdata) = c('Cancer', "Mamografia", "Valores")

# Convertir la columna Valores a tipo numérico
ggdata$Valores <- as.numeric(ggdata$Valores)

ggdata$Mamografia <- factor(ggdata$Mamografia, levels = c("Realizado Mamografía", "No Realizado Mamografía"))

# Calcular los porcentajes por grupo
ggdata <- ggdata %>%
  group_by(Cancer, Mamografia) %>%
  summarise(Valores = sum(Valores)) %>%
  mutate(Percent = Valores / sum(Valores) * 100)

ggplot(data = ggdata, aes(x = Cancer, y = Percent, fill = Mamografia, label = paste0(round(Percent, 1), "%"))) +
  geom_bar(stat = "identity", position = "dodge", color = "black", size = 0.3) +
  labs(x = "Cáncer de Mama", y = "Porcentaje (%)", fill = "Mamografia",
       title = "Comparación de Distribución Porcentual de Realización de Mamografia",
       subtitle = "Fijando Cáncer de Mama y No Cáncer de Mama") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5) +
  scale_fill_manual(values = c("#377eb8","#aec7e8")) + 
  theme_minimal() +
  theme(
    legend.position = "right",   # Colocar la leyenda arriba del gráfico
    legend.box.spacing = unit(0.1, "cm"),  # Ajustar el espacio alrededor de la caja de la leyenda
    plot.title = element_text(size = 15, hjust = 0.5),
    plot.subtitle = element_text(size = 11, hjust = 0.5)
    )
```
                      1    2    3    4    5    7    8
  Breast Cancer    82.0  6.2  1.5  2.7  0.5  2.2  5.0
  No Breast Cancer 91.2  2.3  0.9  1.0  0.3  1.9  2.5

```{r}
ggdata = data.frame(matrix(data = c("Sí","Sí","Sí","Sí","Sí","Sí","Sí","No","No","No","No","No","No","No",
                         "Blanco", "Negro","Indio-Americano", "Asiatico", "Hawaiano", "Multiracial","Hispano",
                         "Blanco", "Negro","Indio-Americano", "Asiatico", "Hawaiano", "Multiracial","Hispano",
                         82.0, 6.2, 1.5, 2.7, 0.5, 2.2, 5.0,
                         91.2, 2.3, 0.9, 1.0, 0.3, 1.9, 2.5), ncol = 3))
colnames(ggdata) = c('Cancer', "Etnia", "Valores")

# Convertir la columna Valores a tipo numérico
ggdata$Valores <- as.numeric(ggdata$Valores)

ggdata$Etnia <- factor(ggdata$Etnia, levels = c("Blanco", "Negro", "Hispano", "Multiracial","Asiatico",'Indio-Americano','Hawaiano'))

# Calcular los porcentajes por grupo
ggdata <- ggdata %>%
  group_by(Cancer, Etnia) %>%
  summarise(Valores = sum(Valores)) %>%
  mutate(Percent = Valores / sum(Valores) * 100)

ggplot(data = ggdata, aes(x = Cancer, y = Percent, fill = Etnia, label = paste0(round(Percent, 1), "%"))) +
  geom_bar(stat = "identity", position = "dodge", color = "black", size = 0.3) +
  labs(x = "Cáncer de Mama", y = "Porcentaje (%)", fill = "Etnia",
       title = "Comparación de Distribución Porcentual de Etnias",
       subtitle = "Fijando Cáncer de Mama y No Cáncer de Mama") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5) +
  scale_fill_manual(values = c("#4575b4","#d73027", "#74c476", "#fdae61", "#abd9e9", "#fee08b", "#9e9ac8")) + 
  theme_minimal() +
  theme(
    legend.position = "right",   # Colocar la leyenda arriba del gráfico
    legend.box.spacing = unit(0.2, "cm"),  # Ajustar el espacio alrededor de la caja de la leyenda
    plot.title = element_text(size = 15, hjust = 0.5),
    plot.subtitle = element_text(size = 11, hjust = 0.5)
    )
```



```{r}
num_data = data[,sapply(data, is.numeric)]

mah_dist <- mahalanobis(num_data, colMeans(num_data), cov(num_data))
outlier_threshold <- quantile(mah_dist, 0.95)
outliers <- which(mah_dist > outlier_threshold)
```

```{r}
#setwd("/Users/manriquecamacho/Library/CloudStorage/OneDrive-UniversidaddeCostaRica/GitHub/Predicción_Cancer/data/processed")

#data = data[-outliers,]

#write.csv(data, "data.csv")
```

```{r}
# Set up multi-panel plotting
par(mfrow = c(1, ncol(num_data)))

colnames(num_data) = c("Edad", "BMI", "Horas de Sueño", "Consumo de Alcohol")

# Loop through each numeric column and plot histogram
for (i in seq_along(num_data)) {
  hist(num_data[, i], main = colnames(num_data)[i], xlab = "Values", col = "#1f77b4", border = "white")
}

# Reset plotting parameters after plotting
par(mfrow = c(1, 1))
```

